# Auto-generated from 2026_LoL_esports_match_data_from_OraclesElixir.csv
LEAGUE_META_CHAMPIONS = {
    "LEC": {  # 124 games
        "TOP": [
            {"name": "Rumble", "picks": 45, "bans": 58, "winrate": 60.0, "tier": "S"},
            {"name": "Varus", "picks": 1, "bans": 86, "winrate": 0.0, "tier": "S"},
            {"name": "K'Sante", "picks": 48, "bans": 19, "winrate": 41.7, "tier": "S"},
            {"name": "Sion", "picks": 29, "bans": 28, "winrate": 55.2, "tier": "S"},
            {"name": "Ambessa", "picks": 20, "bans": 27, "winrate": 60.0, "tier": "A"},
            {"name": "Gnar", "picks": 17, "bans": 23, "winrate": 58.8, "tier": "A"},
            {"name": "Renekton", "picks": 14, "bans": 21, "winrate": 50.0, "tier": "A"},
            {"name": "Akali", "picks": 1, "bans": 22, "winrate": 100.0, "tier": "A"},
            {"name": "Jayce", "picks": 2, "bans": 42, "winrate": 0.0, "tier": "B"},
            {"name": "Poppy", "picks": 5, "bans": 28, "winrate": 40.0, "tier": "B"},
            {"name": "Gwen", "picks": 8, "bans": 15, "winrate": 37.5, "tier": "B"},
            {"name": "Zaahen", "picks": 5, "bans": 7, "winrate": 60.0, "tier": "B"},
            {"name": "Kennen", "picks": 4, "bans": 4, "winrate": 75.0, "tier": "B"},
            {"name": "Rek'Sai", "picks": 5, "bans": 1, "winrate": 80.0, "tier": "B"},
            {"name": "Nidalee", "picks": 1, "bans": 2, "winrate": 0.0, "tier": "B"},
            {"name": "Volibear", "picks": 2, "bans": 0, "winrate": 0.0, "tier": "B"},
            {"name": "Cho'Gath", "picks": 1, "bans": 1, "winrate": 0.0, "tier": "B"},
            {"name": "Gragas", "picks": 2, "bans": 0, "winrate": 100.0, "tier": "B"},
            {"name": "Yasuo", "picks": 2, "bans": 0, "winrate": 50.0, "tier": "B"},
            {"name": "Shen", "picks": 2, "bans": 0, "winrate": 100.0, "tier": "B"},
            {"name": "Ryze", "picks": 1, "bans": 27, "winrate": 0.0, "tier": "C"},
            {"name": "Aatrox", "picks": 7, "bans": 10, "winrate": 14.3, "tier": "C"},
            {"name": "Jax", "picks": 3, "bans": 9, "winrate": 0.0, "tier": "C"},
            {"name": "Aurora", "picks": 4, "bans": 6, "winrate": 50.0, "tier": "C"},
            {"name": "Ornn", "picks": 9, "bans": 0, "winrate": 44.4, "tier": "C"},
            {"name": "Anivia", "picks": 1, "bans": 6, "winrate": 0.0, "tier": "C"},
            {"name": "Kled", "picks": 5, "bans": 1, "winrate": 60.0, "tier": "C"},
            {"name": "Galio", "picks": 1, "bans": 4, "winrate": 0.0, "tier": "C"},
        ],
        "JUNGLE": [
            {"name": "Jarvan IV", "picks": 29, "bans": 47, "winrate": 41.4, "tier": "S"},
            {"name": "Vi", "picks": 32, "bans": 43, "winrate": 53.1, "tier": "S"},
            {"name": "Pantheon", "picks": 31, "bans": 41, "winrate": 38.7, "tier": "S"},
            {"name": "Dr. Mundo", "picks": 18, "bans": 31, "winrate": 61.1, "tier": "S"},
            {"name": "Jayce", "picks": 11, "bans": 42, "winrate": 45.5, "tier": "A"},
            {"name": "Xin Zhao", "picks": 36, "bans": 7, "winrate": 50.0, "tier": "A"},
            {"name": "Wukong", "picks": 23, "bans": 12, "winrate": 52.2, "tier": "A"},
            {"name": "Poppy", "picks": 3, "bans": 28, "winrate": 66.7, "tier": "A"},
            {"name": "Aatrox", "picks": 17, "bans": 10, "winrate": 70.6, "tier": "A"},
            {"name": "Qiyana", "picks": 3, "bans": 6, "winrate": 100.0, "tier": "A"},
            {"name": "Ambessa", "picks": 7, "bans": 27, "winrate": 42.9, "tier": "B"},
            {"name": "Zaahen", "picks": 8, "bans": 7, "winrate": 62.5, "tier": "B"},
            {"name": "Skarner", "picks": 4, "bans": 2, "winrate": 75.0, "tier": "B"},
            {"name": "Sejuani", "picks": 3, "bans": 1, "winrate": 66.7, "tier": "B"},
            {"name": "Malphite", "picks": 3, "bans": 21, "winrate": 0.0, "tier": "C"},
            {"name": "Nocturne", "picks": 9, "bans": 12, "winrate": 33.3, "tier": "C"},
            {"name": "Gwen", "picks": 1, "bans": 15, "winrate": 0.0, "tier": "C"},
            {"name": "Sylas", "picks": 1, "bans": 7, "winrate": 0.0, "tier": "C"},
            {"name": "Naafiri", "picks": 4, "bans": 3, "winrate": 25.0, "tier": "C"},
            {"name": "Trundle", "picks": 2, "bans": 4, "winrate": 50.0, "tier": "C"},
            {"name": "Kha'Zix", "picks": 1, "bans": 0, "winrate": 100.0, "tier": "C"},
            {"name": "Maokai", "picks": 1, "bans": 0, "winrate": 0.0, "tier": "C"},
        ],
        "MID": [
            {"name": "Azir", "picks": 56, "bans": 41, "winrate": 53.6, "tier": "S"},
            {"name": "Orianna", "picks": 31, "bans": 56, "winrate": 58.1, "tier": "S"},
            {"name": "Ryze", "picks": 33, "bans": 27, "winrate": 51.5, "tier": "S"},
            {"name": "Taliyah", "picks": 33, "bans": 20, "winrate": 57.6, "tier": "S"},
            {"name": "Akali", "picks": 5, "bans": 22, "winrate": 60.0, "tier": "A"},
            {"name": "Mel", "picks": 1, "bans": 7, "winrate": 100.0, "tier": "A"},
            {"name": "Zoe", "picks": 2, "bans": 2, "winrate": 100.0, "tier": "A"},
            {"name": "Aurora", "picks": 12, "bans": 6, "winrate": 50.0, "tier": "B"},
            {"name": "Anivia", "picks": 10, "bans": 6, "winrate": 50.0, "tier": "B"},
            {"name": "Ahri", "picks": 14, "bans": 1, "winrate": 57.1, "tier": "B"},
            {"name": "Viktor", "picks": 6, "bans": 1, "winrate": 66.7, "tier": "B"},
            {"name": "Syndra", "picks": 3, "bans": 0, "winrate": 0.0, "tier": "B"},
            {"name": "Twisted Fate", "picks": 1, "bans": 1, "winrate": 0.0, "tier": "B"},
            {"name": "Annie", "picks": 2, "bans": 0, "winrate": 0.0, "tier": "B"},
            {"name": "Karma", "picks": 1, "bans": 19, "winrate": 0.0, "tier": "C"},
            {"name": "Yone", "picks": 9, "bans": 7, "winrate": 22.2, "tier": "C"},
            {"name": "Cassiopeia", "picks": 7, "bans": 5, "winrate": 42.9, "tier": "C"},
            {"name": "Galio", "picks": 8, "bans": 4, "winrate": 37.5, "tier": "C"},
            {"name": "Sylas", "picks": 2, "bans": 7, "winrate": 0.0, "tier": "C"},
            {"name": "Aurelion Sol", "picks": 3, "bans": 2, "winrate": 33.3, "tier": "C"},
            {"name": "LeBlanc", "picks": 3, "bans": 1, "winrate": 0.0, "tier": "C"},
            {"name": "Ekko", "picks": 1, "bans": 0, "winrate": 0.0, "tier": "C"},
            {"name": "Swain", "picks": 1, "bans": 0, "winrate": 0.0, "tier": "C"},
            {"name": "Zed", "picks": 1, "bans": 0, "winrate": 0.0, "tier": "C"},
            {"name": "Lissandra", "picks": 1, "bans": 0, "winrate": 100.0, "tier": "C"},
            {"name": "Yasuo", "picks": 1, "bans": 0, "winrate": 100.0, "tier": "C"},
            {"name": "Hwei", "picks": 1, "bans": 0, "winrate": 0.0, "tier": "C"},
        ],
        "ADC": [
            {"name": "Varus", "picks": 19, "bans": 86, "winrate": 68.4, "tier": "S"},
            {"name": "Yunara", "picks": 45, "bans": 46, "winrate": 55.6, "tier": "S"},
            {"name": "Corki", "picks": 41, "bans": 8, "winrate": 39.0, "tier": "A"},
            {"name": "Aphelios", "picks": 22, "bans": 16, "winrate": 45.5, "tier": "A"},
            {"name": "Ezreal", "picks": 26, "bans": 10, "winrate": 42.3, "tier": "A"},
            {"name": "Caitlyn", "picks": 14, "bans": 21, "winrate": 64.3, "tier": "A"},
            {"name": "Kai'Sa", "picks": 15, "bans": 17, "winrate": 60.0, "tier": "A"},
            {"name": "Jhin", "picks": 18, "bans": 8, "winrate": 50.0, "tier": "B"},
            {"name": "Sivir", "picks": 13, "bans": 7, "winrate": 53.8, "tier": "B"},
            {"name": "Xayah", "picks": 8, "bans": 7, "winrate": 75.0, "tier": "B"},
            {"name": "Ashe", "picks": 11, "bans": 4, "winrate": 63.6, "tier": "B"},
            {"name": "Zeri", "picks": 1, "bans": 2, "winrate": 100.0, "tier": "B"},
            {"name": "Smolder", "picks": 1, "bans": 1, "winrate": 0.0, "tier": "B"},
            {"name": "Kalista", "picks": 2, "bans": 0, "winrate": 50.0, "tier": "B"},
            {"name": "Lucian", "picks": 4, "bans": 2, "winrate": 0.0, "tier": "C"},
            {"name": "Miss Fortune", "picks": 3, "bans": 2, "winrate": 0.0, "tier": "C"},
            {"name": "Jinx", "picks": 4, "bans": 0, "winrate": 0.0, "tier": "C"},
            {"name": "Seraphine", "picks": 1, "bans": 3, "winrate": 0.0, "tier": "C"},
        ],
        "SUPPORT": [
            {"name": "Nautilus", "picks": 29, "bans": 51, "winrate": 34.5, "tier": "S"},
            {"name": "Neeko", "picks": 22, "bans": 49, "winrate": 45.5, "tier": "S"},
            {"name": "Bard", "picks": 31, "bans": 26, "winrate": 58.1, "tier": "S"},
            {"name": "Alistar", "picks": 34, "bans": 22, "winrate": 58.8, "tier": "S"},
            {"name": "Rakan", "picks": 30, "bans": 17, "winrate": 60.0, "tier": "A"},
            {"name": "Nami", "picks": 20, "bans": 17, "winrate": 60.0, "tier": "A"},
            {"name": "Karma", "picks": 15, "bans": 19, "winrate": 40.0, "tier": "B"},
            {"name": "Lulu", "picks": 16, "bans": 6, "winrate": 43.8, "tier": "B"},
            {"name": "Braum", "picks": 8, "bans": 12, "winrate": 50.0, "tier": "B"},
            {"name": "Rell", "picks": 12, "bans": 4, "winrate": 50.0, "tier": "B"},
            {"name": "Seraphine", "picks": 11, "bans": 3, "winrate": 54.5, "tier": "B"},
            {"name": "Leona", "picks": 5, "bans": 0, "winrate": 80.0, "tier": "B"},
            {"name": "Elise", "picks": 2, "bans": 1, "winrate": 50.0, "tier": "B"},
            {"name": "Pyke", "picks": 2, "bans": 0, "winrate": 0.0, "tier": "B"},
            {"name": "Milio", "picks": 2, "bans": 0, "winrate": 0.0, "tier": "B"},
            {"name": "Thresh", "picks": 4, "bans": 2, "winrate": 25.0, "tier": "C"},
            {"name": "Renata Glasc", "picks": 3, "bans": 2, "winrate": 33.3, "tier": "C"},
            {"name": "Taric", "picks": 1, "bans": 0, "winrate": 0.0, "tier": "C"},
            {"name": "Janna", "picks": 1, "bans": 0, "winrate": 0.0, "tier": "C"},
        ],
    },
    "LCK": {  # 138 games
        "TOP": [
            {"name": "Rumble", "picks": 18, "bans": 86, "winrate": 55.6, "tier": "S"},
            {"name": "Jayce", "picks": 11, "bans": 74, "winrate": 54.5, "tier": "S"},
            {"name": "Varus", "picks": 1, "bans": 69, "winrate": 100.0, "tier": "S"},
            {"name": "Gwen", "picks": 22, "bans": 30, "winrate": 72.7, "tier": "S"},
            {"name": "Ambessa", "picks": 22, "bans": 35, "winrate": 45.5, "tier": "A"},
            {"name": "Renekton", "picks": 31, "bans": 19, "winrate": 45.2, "tier": "A"},
            {"name": "K'Sante", "picks": 28, "bans": 17, "winrate": 53.6, "tier": "A"},
            {"name": "Gnar", "picks": 26, "bans": 16, "winrate": 57.7, "tier": "A"},
            {"name": "Akali", "picks": 1, "bans": 22, "winrate": 100.0, "tier": "A"},
            {"name": "Ryze", "picks": 1, "bans": 14, "winrate": 100.0, "tier": "A"},
            {"name": "Sion", "picks": 28, "bans": 9, "winrate": 25.0, "tier": "B"},
            {"name": "Kennen", "picks": 14, "bans": 16, "winrate": 50.0, "tier": "B"},
            {"name": "Aurora", "picks": 9, "bans": 17, "winrate": 33.3, "tier": "B"},
            {"name": "Rek'Sai", "picks": 16, "bans": 6, "winrate": 50.0, "tier": "B"},
            {"name": "Zaahen", "picks": 15, "bans": 2, "winrate": 73.3, "tier": "B"},
            {"name": "Olaf", "picks": 2, "bans": 1, "winrate": 100.0, "tier": "B"},
            {"name": "Gragas", "picks": 2, "bans": 0, "winrate": 0.0, "tier": "B"},
            {"name": "Jax", "picks": 9, "bans": 8, "winrate": 33.3, "tier": "C"},
            {"name": "Yorick", "picks": 6, "bans": 6, "winrate": 33.3, "tier": "C"},
            {"name": "Sylas", "picks": 2, "bans": 9, "winrate": 50.0, "tier": "C"},
            {"name": "Ornn", "picks": 6, "bans": 1, "winrate": 33.3, "tier": "C"},
            {"name": "Aatrox", "picks": 5, "bans": 1, "winrate": 40.0, "tier": "C"},
            {"name": "Vayne", "picks": 1, "bans": 0, "winrate": 100.0, "tier": "C"},
        ],
        "JUNGLE": [
            {"name": "Vi", "picks": 29, "bans": 45, "winrate": 51.7, "tier": "S"},
            {"name": "Pantheon", "picks": 31, "bans": 35, "winrate": 64.5, "tier": "S"},
            {"name": "Nautilus", "picks": 1, "bans": 42, "winrate": 100.0, "tier": "S"},
            {"name": "Jayce", "picks": 5, "bans": 74, "winrate": 20.0, "tier": "A"},
            {"name": "Malphite", "picks": 6, "bans": 64, "winrate": 16.7, "tier": "A"},
            {"name": "Jarvan IV", "picks": 38, "bans": 22, "winrate": 50.0, "tier": "A"},
            {"name": "Nocturne", "picks": 18, "bans": 38, "winrate": 50.0, "tier": "A"},
            {"name": "Xin Zhao", "picks": 39, "bans": 10, "winrate": 46.2, "tier": "A"},
            {"name": "Ambessa", "picks": 13, "bans": 35, "winrate": 53.8, "tier": "A"},
            {"name": "Wukong", "picks": 30, "bans": 11, "winrate": 43.3, "tier": "A"},
            {"name": "Lee Sin", "picks": 8, "bans": 12, "winrate": 75.0, "tier": "A"},
            {"name": "Jax", "picks": 2, "bans": 8, "winrate": 100.0, "tier": "A"},
            {"name": "Dr. Mundo", "picks": 10, "bans": 7, "winrate": 60.0, "tier": "B"},
            {"name": "Trundle", "picks": 8, "bans": 6, "winrate": 75.0, "tier": "B"},
            {"name": "Olaf", "picks": 1, "bans": 1, "winrate": 100.0, "tier": "B"},
            {"name": "Maokai", "picks": 2, "bans": 0, "winrate": 100.0, "tier": "B"},
            {"name": "Kha'Zix", "picks": 1, "bans": 1, "winrate": 0.0, "tier": "B"},
            {"name": "Poppy", "picks": 1, "bans": 31, "winrate": 0.0, "tier": "C"},
            {"name": "Aatrox", "picks": 11, "bans": 1, "winrate": 36.4, "tier": "C"},
            {"name": "Sylas", "picks": 2, "bans": 9, "winrate": 50.0, "tier": "C"},
            {"name": "Qiyana", "picks": 3, "bans": 5, "winrate": 0.0, "tier": "C"},
            {"name": "Naafiri", "picks": 5, "bans": 1, "winrate": 40.0, "tier": "C"},
            {"name": "Sejuani", "picks": 4, "bans": 1, "winrate": 0.0, "tier": "C"},
            {"name": "Zaahen", "picks": 3, "bans": 2, "winrate": 33.3, "tier": "C"},
            {"name": "Hecarim", "picks": 1, "bans": 0, "winrate": 0.0, "tier": "C"},
            {"name": "Lillia", "picks": 1, "bans": 0, "winrate": 100.0, "tier": "C"},
            {"name": "Rammus", "picks": 1, "bans": 0, "winrate": 0.0, "tier": "C"},
            {"name": "Zac", "picks": 1, "bans": 0, "winrate": 100.0, "tier": "C"},
            {"name": "Nidalee", "picks": 1, "bans": 0, "winrate": 100.0, "tier": "C"},
        ],
        "MID": [
            {"name": "Orianna", "picks": 29, "bans": 56, "winrate": 48.3, "tier": "S"},
            {"name": "Jayce", "picks": 1, "bans": 74, "winrate": 100.0, "tier": "S"},
            {"name": "Azir", "picks": 35, "bans": 37, "winrate": 40.0, "tier": "S"},
            {"name": "Ryze", "picks": 40, "bans": 14, "winrate": 60.0, "tier": "A"},
            {"name": "Ahri", "picks": 17, "bans": 12, "winrate": 64.7, "tier": "A"},
            {"name": "Sylas", "picks": 5, "bans": 9, "winrate": 80.0, "tier": "A"},
            {"name": "Taliyah", "picks": 34, "bans": 4, "winrate": 38.2, "tier": "B"},
            {"name": "Aurora", "picks": 16, "bans": 17, "winrate": 43.8, "tier": "B"},
            {"name": "Akali", "picks": 11, "bans": 22, "winrate": 36.4, "tier": "B"},
            {"name": "Cassiopeia", "picks": 10, "bans": 11, "winrate": 50.0, "tier": "B"},
            {"name": "Galio", "picks": 13, "bans": 6, "winrate": 61.5, "tier": "B"},
            {"name": "Zoe", "picks": 10, "bans": 8, "winrate": 70.0, "tier": "B"},
            {"name": "Yone", "picks": 8, "bans": 10, "winrate": 50.0, "tier": "B"},
            {"name": "LeBlanc", "picks": 3, "bans": 9, "winrate": 66.7, "tier": "B"},
            {"name": "Twisted Fate", "picks": 6, "bans": 6, "winrate": 66.7, "tier": "B"},
            {"name": "Annie", "picks": 4, "bans": 1, "winrate": 75.0, "tier": "B"},
            {"name": "Tristana", "picks": 2, "bans": 0, "winrate": 50.0, "tier": "B"},
            {"name": "Anivia", "picks": 8, "bans": 7, "winrate": 37.5, "tier": "C"},
            {"name": "Syndra", "picks": 11, "bans": 2, "winrate": 45.5, "tier": "C"},
            {"name": "Viktor", "picks": 7, "bans": 3, "winrate": 28.6, "tier": "C"},
            {"name": "Ziggs", "picks": 2, "bans": 8, "winrate": 50.0, "tier": "C"},
            {"name": "Mel", "picks": 1, "bans": 3, "winrate": 0.0, "tier": "C"},
            {"name": "Ekko", "picks": 1, "bans": 0, "winrate": 100.0, "tier": "C"},
            {"name": "Smolder", "picks": 1, "bans": 0, "winrate": 0.0, "tier": "C"},
            {"name": "Malzahar", "picks": 1, "bans": 0, "winrate": 0.0, "tier": "C"},
        ],
        "ADC": [
            {"name": "Varus", "picks": 24, "bans": 69, "winrate": 54.2, "tier": "S"},
            {"name": "Yunara", "picks": 41, "bans": 33, "winrate": 53.7, "tier": "S"},
            {"name": "Corki", "picks": 31, "bans": 15, "winrate": 45.2, "tier": "A"},
            {"name": "Lucian", "picks": 20, "bans": 25, "winrate": 45.0, "tier": "A"},
            {"name": "Ezreal", "picks": 30, "bans": 13, "winrate": 43.3, "tier": "A"},
            {"name": "Sivir", "picks": 19, "bans": 17, "winrate": 57.9, "tier": "A"},
            {"name": "Aphelios", "picks": 19, "bans": 13, "winrate": 52.6, "tier": "B"},
            {"name": "Ashe", "picks": 16, "bans": 9, "winrate": 62.5, "tier": "B"},
            {"name": "Jhin", "picks": 20, "bans": 4, "winrate": 45.0, "tier": "B"},
            {"name": "Kalista", "picks": 11, "bans": 8, "winrate": 45.5, "tier": "B"},
            {"name": "Kai'Sa", "picks": 11, "bans": 6, "winrate": 72.7, "tier": "B"},
            {"name": "Xayah", "picks": 6, "bans": 3, "winrate": 66.7, "tier": "B"},
            {"name": "Ziggs", "picks": 8, "bans": 8, "winrate": 37.5, "tier": "C"},
            {"name": "Miss Fortune", "picks": 6, "bans": 4, "winrate": 33.3, "tier": "C"},
            {"name": "Caitlyn", "picks": 6, "bans": 3, "winrate": 33.3, "tier": "C"},
            {"name": "Zeri", "picks": 2, "bans": 3, "winrate": 50.0, "tier": "C"},
            {"name": "Jinx", "picks": 4, "bans": 0, "winrate": 50.0, "tier": "C"},
            {"name": "Mel", "picks": 1, "bans": 3, "winrate": 0.0, "tier": "C"},
            {"name": "Tristana", "picks": 1, "bans": 0, "winrate": 0.0, "tier": "C"},
        ],
        "SUPPORT": [
            {"name": "Neeko", "picks": 26, "bans": 59, "winrate": 61.5, "tier": "S"},
            {"name": "Bard", "picks": 21, "bans": 48, "winrate": 57.1, "tier": "S"},
            {"name": "Nautilus", "picks": 22, "bans": 42, "winrate": 50.0, "tier": "S"},
            {"name": "Lulu", "picks": 20, "bans": 24, "winrate": 45.0, "tier": "A"},
            {"name": "Karma", "picks": 15, "bans": 25, "winrate": 53.3, "tier": "A"},
            {"name": "Rakan", "picks": 24, "bans": 10, "winrate": 62.5, "tier": "A"},
            {"name": "Alistar", "picks": 24, "bans": 16, "winrate": 37.5, "tier": "B"},
            {"name": "Pantheon", "picks": 3, "bans": 35, "winrate": 33.3, "tier": "B"},
            {"name": "Poppy", "picks": 6, "bans": 31, "winrate": 33.3, "tier": "B"},
            {"name": "Nami", "picks": 16, "bans": 15, "winrate": 37.5, "tier": "B"},
            {"name": "Leona", "picks": 14, "bans": 10, "winrate": 42.9, "tier": "B"},
            {"name": "Rell", "picks": 13, "bans": 6, "winrate": 46.2, "tier": "B"},
            {"name": "Seraphine", "picks": 14, "bans": 0, "winrate": 78.6, "tier": "B"},
            {"name": "Thresh", "picks": 10, "bans": 0, "winrate": 60.0, "tier": "B"},
            {"name": "Elise", "picks": 5, "bans": 2, "winrate": 60.0, "tier": "B"},
            {"name": "Yuumi", "picks": 3, "bans": 0, "winrate": 33.3, "tier": "B"},
            {"name": "Braum", "picks": 13, "bans": 6, "winrate": 30.8, "tier": "C"},
            {"name": "Renata Glasc", "picks": 12, "bans": 6, "winrate": 41.7, "tier": "C"},
            {"name": "Anivia", "picks": 3, "bans": 7, "winrate": 33.3, "tier": "C"},
            {"name": "Blitzcrank", "picks": 2, "bans": 4, "winrate": 50.0, "tier": "C"},
            {"name": "Milio", "picks": 4, "bans": 0, "winrate": 50.0, "tier": "C"},
            {"name": "Soraka", "picks": 1, "bans": 0, "winrate": 0.0, "tier": "C"},
            {"name": "Lissandra", "picks": 1, "bans": 0, "winrate": 100.0, "tier": "C"},
            {"name": "Tahm Kench", "picks": 1, "bans": 0, "winrate": 0.0, "tier": "C"},
            {"name": "Shen", "picks": 1, "bans": 0, "winrate": 100.0, "tier": "C"},
            {"name": "Sona", "picks": 1, "bans": 0, "winrate": 100.0, "tier": "C"},
            {"name": "Pyke", "picks": 1, "bans": 0, "winrate": 0.0, "tier": "C"},
        ],
    },
    "LPL": {  # 214 games
        "TOP": [
            {"name": "Jayce", "picks": 5, "bans": 148, "winrate": 0.0, "tier": "S"},
            {"name": "Rumble", "picks": 53, "bans": 76, "winrate": 66.0, "tier": "S"},
            {"name": "Ambessa", "picks": 43, "bans": 54, "winrate": 60.5, "tier": "S"},
            {"name": "Malphite", "picks": 1, "bans": 109, "winrate": 0.0, "tier": "A"},
            {"name": "Varus", "picks": 7, "bans": 87, "winrate": 28.6, "tier": "A"},
            {"name": "Poppy", "picks": 2, "bans": 85, "winrate": 50.0, "tier": "A"},
            {"name": "Renekton", "picks": 51, "bans": 32, "winrate": 47.1, "tier": "A"},
            {"name": "Sion", "picks": 56, "bans": 19, "winrate": 48.2, "tier": "A"},
            {"name": "Gnar", "picks": 32, "bans": 20, "winrate": 59.4, "tier": "A"},
            {"name": "Yorick", "picks": 13, "bans": 16, "winrate": 76.9, "tier": "A"},
            {"name": "Naafiri", "picks": 1, "bans": 6, "winrate": 100.0, "tier": "A"},
            {"name": "K'Sante", "picks": 42, "bans": 14, "winrate": 33.3, "tier": "B"},
            {"name": "Gwen", "picks": 17, "bans": 25, "winrate": 41.2, "tier": "B"},
            {"name": "Zaahen", "picks": 22, "bans": 16, "winrate": 45.5, "tier": "B"},
            {"name": "Jax", "picks": 15, "bans": 16, "winrate": 60.0, "tier": "B"},
            {"name": "Rek'Sai", "picks": 17, "bans": 7, "winrate": 58.8, "tier": "B"},
            {"name": "Ornn", "picks": 14, "bans": 4, "winrate": 57.1, "tier": "B"},
            {"name": "Mordekaiser", "picks": 3, "bans": 0, "winrate": 0.0, "tier": "B"},
            {"name": "Gragas", "picks": 2, "bans": 0, "winrate": 50.0, "tier": "B"},
            {"name": "Vladimir", "picks": 2, "bans": 0, "winrate": 50.0, "tier": "B"},
            {"name": "Gangplank", "picks": 2, "bans": 0, "winrate": 0.0, "tier": "B"},
            {"name": "Sylas", "picks": 1, "bans": 38, "winrate": 0.0, "tier": "C"},
            {"name": "Aurora", "picks": 10, "bans": 22, "winrate": 40.0, "tier": "C"},
            {"name": "Kennen", "picks": 7, "bans": 8, "winrate": 28.6, "tier": "C"},
            {"name": "Galio", "picks": 1, "bans": 12, "winrate": 0.0, "tier": "C"},
            {"name": "Aatrox", "picks": 5, "bans": 2, "winrate": 60.0, "tier": "C"},
            {"name": "Udyr", "picks": 1, "bans": 3, "winrate": 0.0, "tier": "C"},
            {"name": "Yasuo", "picks": 1, "bans": 0, "winrate": 0.0, "tier": "C"},
            {"name": "Nidalee", "picks": 1, "bans": 0, "winrate": 0.0, "tier": "C"},
            {"name": "Camille", "picks": 1, "bans": 0, "winrate": 0.0, "tier": "C"},
        ],
        "JUNGLE": [
            {"name": "Jayce", "picks": 8, "bans": 148, "winrate": 62.5, "tier": "S"},
            {"name": "Jarvan IV", "picks": 51, "bans": 74, "winrate": 60.8, "tier": "S"},
            {"name": "Malphite", "picks": 15, "bans": 109, "winrate": 53.3, "tier": "S"},
            {"name": "Vi", "picks": 47, "bans": 51, "winrate": 51.1, "tier": "S"},
            {"name": "Poppy", "picks": 13, "bans": 85, "winrate": 69.2, "tier": "S"},
            {"name": "Xin Zhao", "picks": 60, "bans": 19, "winrate": 58.3, "tier": "A"},
            {"name": "Wukong", "picks": 45, "bans": 28, "winrate": 44.4, "tier": "A"},
            {"name": "Pantheon", "picks": 44, "bans": 27, "winrate": 40.9, "tier": "A"},
            {"name": "Ambessa", "picks": 9, "bans": 54, "winrate": 22.2, "tier": "B"},
            {"name": "Nocturne", "picks": 28, "bans": 32, "winrate": 42.9, "tier": "B"},
            {"name": "Qiyana", "picks": 29, "bans": 17, "winrate": 55.2, "tier": "B"},
            {"name": "Dr. Mundo", "picks": 21, "bans": 14, "winrate": 38.1, "tier": "B"},
            {"name": "Naafiri", "picks": 8, "bans": 6, "winrate": 62.5, "tier": "B"},
            {"name": "Sejuani", "picks": 4, "bans": 0, "winrate": 75.0, "tier": "B"},
            {"name": "Maokai", "picks": 4, "bans": 0, "winrate": 75.0, "tier": "B"},
            {"name": "Skarner", "picks": 2, "bans": 1, "winrate": 50.0, "tier": "B"},
            {"name": "Lee Sin", "picks": 3, "bans": 0, "winrate": 33.3, "tier": "B"},
            {"name": "Kha'Zix", "picks": 3, "bans": 0, "winrate": 66.7, "tier": "B"},
            {"name": "Kindred", "picks": 1, "bans": 1, "winrate": 0.0, "tier": "B"},
            {"name": "Olaf", "picks": 1, "bans": 1, "winrate": 100.0, "tier": "B"},
            {"name": "Sylas", "picks": 2, "bans": 38, "winrate": 0.0, "tier": "C"},
            {"name": "Trundle", "picks": 17, "bans": 7, "winrate": 35.3, "tier": "C"},
            {"name": "Zaahen", "picks": 2, "bans": 16, "winrate": 50.0, "tier": "C"},
            {"name": "Jax", "picks": 1, "bans": 16, "winrate": 0.0, "tier": "C"},
            {"name": "Viego", "picks": 5, "bans": 2, "winrate": 20.0, "tier": "C"},
            {"name": "Aatrox", "picks": 3, "bans": 2, "winrate": 0.0, "tier": "C"},
            {"name": "Zac", "picks": 1, "bans": 0, "winrate": 100.0, "tier": "C"},
            {"name": "Warwick", "picks": 1, "bans": 0, "winrate": 100.0, "tier": "C"},
        ],
        "MID": [
            {"name": "Orianna", "picks": 30, "bans": 140, "winrate": 56.7, "tier": "S"},
            {"name": "Ryze", "picks": 59, "bans": 32, "winrate": 52.5, "tier": "A"},
            {"name": "Azir", "picks": 65, "bans": 25, "winrate": 50.8, "tier": "A"},
            {"name": "Akali", "picks": 19, "bans": 61, "winrate": 52.6, "tier": "A"},
            {"name": "Ahri", "picks": 31, "bans": 22, "winrate": 51.6, "tier": "A"},
            {"name": "LeBlanc", "picks": 11, "bans": 32, "winrate": 72.7, "tier": "A"},
            {"name": "Annie", "picks": 1, "bans": 4, "winrate": 100.0, "tier": "A"},
            {"name": "Taliyah", "picks": 40, "bans": 12, "winrate": 42.5, "tier": "B"},
            {"name": "Sylas", "picks": 10, "bans": 38, "winrate": 50.0, "tier": "B"},
            {"name": "Aurora", "picks": 25, "bans": 22, "winrate": 40.0, "tier": "B"},
            {"name": "Syndra", "picks": 27, "bans": 10, "winrate": 40.7, "tier": "B"},
            {"name": "Galio", "picks": 19, "bans": 12, "winrate": 52.6, "tier": "B"},
            {"name": "Cassiopeia", "picks": 14, "bans": 13, "winrate": 57.1, "tier": "B"},
            {"name": "Yone", "picks": 14, "bans": 10, "winrate": 71.4, "tier": "B"},
            {"name": "Twisted Fate", "picks": 8, "bans": 10, "winrate": 62.5, "tier": "B"},
            {"name": "Zoe", "picks": 6, "bans": 0, "winrate": 66.7, "tier": "B"},
            {"name": "Malzahar", "picks": 2, "bans": 1, "winrate": 100.0, "tier": "B"},
            {"name": "Swain", "picks": 3, "bans": 0, "winrate": 33.3, "tier": "B"},
            {"name": "Smolder", "picks": 2, "bans": 0, "winrate": 50.0, "tier": "B"},
            {"name": "Viktor", "picks": 16, "bans": 9, "winrate": 31.2, "tier": "C"},
            {"name": "Anivia", "picks": 11, "bans": 8, "winrate": 18.2, "tier": "C"},
            {"name": "Ziggs", "picks": 6, "bans": 10, "winrate": 50.0, "tier": "C"},
            {"name": "Mel", "picks": 4, "bans": 1, "winrate": 25.0, "tier": "C"},
            {"name": "Aurelion Sol", "picks": 1, "bans": 0, "winrate": 0.0, "tier": "C"},
            {"name": "Ekko", "picks": 1, "bans": 0, "winrate": 0.0, "tier": "C"},
            {"name": "Hwei", "picks": 1, "bans": 0, "winrate": 100.0, "tier": "C"},
            {"name": "Diana", "picks": 1, "bans": 0, "winrate": 100.0, "tier": "C"},
            {"name": "Lissandra", "picks": 1, "bans": 0, "winrate": 100.0, "tier": "C"},
        ],
        "ADC": [
            {"name": "Varus", "picks": 48, "bans": 87, "winrate": 52.1, "tier": "S"},
            {"name": "Yunara", "picks": 64, "bans": 52, "winrate": 45.3, "tier": "S"},
            {"name": "Sivir", "picks": 40, "bans": 36, "winrate": 57.5, "tier": "A"},
            {"name": "Miss Fortune", "picks": 46, "bans": 28, "winrate": 54.3, "tier": "A"},
            {"name": "Aphelios", "picks": 31, "bans": 37, "winrate": 41.9, "tier": "A"},
            {"name": "Kai'Sa", "picks": 25, "bans": 37, "winrate": 60.0, "tier": "A"},
            {"name": "Corki", "picks": 46, "bans": 15, "winrate": 50.0, "tier": "A"},
            {"name": "Ashe", "picks": 28, "bans": 20, "winrate": 53.6, "tier": "B"},
            {"name": "Ezreal", "picks": 24, "bans": 15, "winrate": 54.2, "tier": "B"},
            {"name": "Jhin", "picks": 30, "bans": 7, "winrate": 36.7, "tier": "B"},
            {"name": "Ziggs", "picks": 4, "bans": 10, "winrate": 75.0, "tier": "B"},
            {"name": "Jinx", "picks": 5, "bans": 4, "winrate": 80.0, "tier": "B"},
            {"name": "Tristana", "picks": 1, "bans": 1, "winrate": 0.0, "tier": "B"},
            {"name": "Lucian", "picks": 8, "bans": 8, "winrate": 25.0, "tier": "C"},
            {"name": "Caitlyn", "picks": 5, "bans": 7, "winrate": 20.0, "tier": "C"},
            {"name": "Kalista", "picks": 8, "bans": 2, "winrate": 50.0, "tier": "C"},
            {"name": "Xayah", "picks": 4, "bans": 3, "winrate": 50.0, "tier": "C"},
            {"name": "Draven", "picks": 5, "bans": 1, "winrate": 60.0, "tier": "C"},
            {"name": "Zeri", "picks": 4, "bans": 1, "winrate": 50.0, "tier": "C"},
            {"name": "Senna", "picks": 1, "bans": 0, "winrate": 0.0, "tier": "C"},
            {"name": "Kog'Maw", "picks": 1, "bans": 0, "winrate": 100.0, "tier": "C"},
        ],
        "SUPPORT": [
            {"name": "Neeko", "picks": 36, "bans": 122, "winrate": 63.9, "tier": "S"},
            {"name": "Poppy", "picks": 8, "bans": 85, "winrate": 62.5, "tier": "S"},
            {"name": "Nautilus", "picks": 40, "bans": 43, "winrate": 47.5, "tier": "A"},
            {"name": "Alistar", "picks": 54, "bans": 27, "winrate": 57.4, "tier": "A"},
            {"name": "Bard", "picks": 33, "bans": 40, "winrate": 57.6, "tier": "A"},
            {"name": "Lulu", "picks": 36, "bans": 29, "winrate": 52.8, "tier": "A"},
            {"name": "Rakan", "picks": 31, "bans": 22, "winrate": 51.6, "tier": "A"},
            {"name": "Pantheon", "picks": 1, "bans": 27, "winrate": 100.0, "tier": "A"},
            {"name": "Anivia", "picks": 1, "bans": 8, "winrate": 100.0, "tier": "A"},
            {"name": "Karma", "picks": 21, "bans": 24, "winrate": 47.6, "tier": "B"},
            {"name": "Rell", "picks": 33, "bans": 6, "winrate": 39.4, "tier": "B"},
            {"name": "Braum", "picks": 18, "bans": 14, "winrate": 50.0, "tier": "B"},
            {"name": "Thresh", "picks": 21, "bans": 9, "winrate": 52.4, "tier": "B"},
            {"name": "Seraphine", "picks": 23, "bans": 2, "winrate": 47.8, "tier": "B"},
            {"name": "Shen", "picks": 3, "bans": 0, "winrate": 66.7, "tier": "B"},
            {"name": "Elise", "picks": 3, "bans": 0, "winrate": 33.3, "tier": "B"},
            {"name": "Leona", "picks": 23, "bans": 10, "winrate": 39.1, "tier": "C"},
            {"name": "Renata Glasc", "picks": 13, "bans": 14, "winrate": 30.8, "tier": "C"},
            {"name": "Nami", "picks": 21, "bans": 6, "winrate": 42.9, "tier": "C"},
            {"name": "Blitzcrank", "picks": 3, "bans": 1, "winrate": 0.0, "tier": "C"},
            {"name": "Yuumi", "picks": 4, "bans": 0, "winrate": 0.0, "tier": "C"},
            {"name": "Pyke", "picks": 1, "bans": 0, "winrate": 100.0, "tier": "C"},
            {"name": "Rammus", "picks": 1, "bans": 0, "winrate": 0.0, "tier": "C"},
        ],
    },
    "LCS": {  # 59 games
        "TOP": [
            {"name": "Rumble", "picks": 15, "bans": 27, "winrate": 26.7, "tier": "S"},
            {"name": "Varus", "picks": 1, "bans": 38, "winrate": 100.0, "tier": "S"},
            {"name": "Jayce", "picks": 1, "bans": 27, "winrate": 100.0, "tier": "S"},
            {"name": "Ambessa", "picks": 8, "bans": 18, "winrate": 87.5, "tier": "S"},
            {"name": "Aurora", "picks": 6, "bans": 15, "winrate": 83.3, "tier": "S"},
            {"name": "Renekton", "picks": 19, "bans": 8, "winrate": 36.8, "tier": "A"},
            {"name": "Sion", "picks": 16, "bans": 3, "winrate": 50.0, "tier": "A"},
            {"name": "K'Sante", "picks": 14, "bans": 4, "winrate": 50.0, "tier": "A"},
            {"name": "Poppy", "picks": 1, "bans": 10, "winrate": 100.0, "tier": "A"},
            {"name": "Zaahen", "picks": 2, "bans": 3, "winrate": 100.0, "tier": "A"},
            {"name": "Gnar", "picks": 10, "bans": 4, "winrate": 50.0, "tier": "B"},
            {"name": "Galio", "picks": 4, "bans": 3, "winrate": 75.0, "tier": "B"},
            {"name": "Rek'Sai", "picks": 3, "bans": 0, "winrate": 66.7, "tier": "B"},
            {"name": "Ornn", "picks": 1, "bans": 2, "winrate": 100.0, "tier": "B"},
            {"name": "Jax", "picks": 3, "bans": 0, "winrate": 0.0, "tier": "B"},
            {"name": "Vayne", "picks": 1, "bans": 2, "winrate": 100.0, "tier": "B"},
            {"name": "Kennen", "picks": 2, "bans": 0, "winrate": 0.0, "tier": "B"},
            {"name": "Olaf", "picks": 1, "bans": 1, "winrate": 0.0, "tier": "B"},
            {"name": "Yorick", "picks": 1, "bans": 1, "winrate": 100.0, "tier": "B"},
            {"name": "Gwen", "picks": 3, "bans": 16, "winrate": 0.0, "tier": "C"},
            {"name": "Aatrox", "picks": 2, "bans": 2, "winrate": 50.0, "tier": "C"},
            {"name": "Mordekaiser", "picks": 1, "bans": 0, "winrate": 0.0, "tier": "C"},
            {"name": "Nasus", "picks": 1, "bans": 0, "winrate": 100.0, "tier": "C"},
            {"name": "Irelia", "picks": 1, "bans": 0, "winrate": 100.0, "tier": "C"},
            {"name": "Camille", "picks": 1, "bans": 0, "winrate": 0.0, "tier": "C"},
        ],
        "JUNGLE": [
            {"name": "Pantheon", "picks": 10, "bans": 28, "winrate": 60.0, "tier": "S"},
            {"name": "Jarvan IV", "picks": 13, "bans": 23, "winrate": 69.2, "tier": "S"},
            {"name": "Nocturne", "picks": 9, "bans": 18, "winrate": 66.7, "tier": "S"},
            {"name": "Vi", "picks": 17, "bans": 11, "winrate": 29.4, "tier": "A"},
            {"name": "Ambessa", "picks": 3, "bans": 18, "winrate": 66.7, "tier": "A"},
            {"name": "Xin Zhao", "picks": 12, "bans": 8, "winrate": 41.7, "tier": "A"},
            {"name": "Wukong", "picks": 17, "bans": 3, "winrate": 35.3, "tier": "A"},
            {"name": "Malphite", "picks": 5, "bans": 14, "winrate": 60.0, "tier": "A"},
            {"name": "Trundle", "picks": 6, "bans": 8, "winrate": 66.7, "tier": "A"},
            {"name": "Jayce", "picks": 1, "bans": 27, "winrate": 0.0, "tier": "B"},
            {"name": "Dr. Mundo", "picks": 4, "bans": 5, "winrate": 50.0, "tier": "B"},
            {"name": "Zaahen", "picks": 3, "bans": 3, "winrate": 66.7, "tier": "B"},
            {"name": "Volibear", "picks": 2, "bans": 1, "winrate": 100.0, "tier": "B"},
            {"name": "Ornn", "picks": 1, "bans": 2, "winrate": 100.0, "tier": "B"},
            {"name": "Nidalee", "picks": 2, "bans": 0, "winrate": 50.0, "tier": "B"},
            {"name": "Sejuani", "picks": 1, "bans": 1, "winrate": 0.0, "tier": "B"},
            {"name": "Gwen", "picks": 1, "bans": 16, "winrate": 0.0, "tier": "C"},
            {"name": "Aatrox", "picks": 3, "bans": 2, "winrate": 33.3, "tier": "C"},
            {"name": "Qiyana", "picks": 3, "bans": 1, "winrate": 33.3, "tier": "C"},
            {"name": "Diana", "picks": 1, "bans": 0, "winrate": 0.0, "tier": "C"},
            {"name": "Lee Sin", "picks": 1, "bans": 0, "winrate": 0.0, "tier": "C"},
            {"name": "Ivern", "picks": 1, "bans": 0, "winrate": 100.0, "tier": "C"},
            {"name": "Maokai", "picks": 1, "bans": 0, "winrate": 100.0, "tier": "C"},
            {"name": "Skarner", "picks": 1, "bans": 0, "winrate": 100.0, "tier": "C"},
        ],
        "MID": [
            {"name": "Orianna", "picks": 16, "bans": 17, "winrate": 43.8, "tier": "S"},
            {"name": "Azir", "picks": 17, "bans": 16, "winrate": 58.8, "tier": "S"},
            {"name": "Jayce", "picks": 1, "bans": 27, "winrate": 100.0, "tier": "S"},
            {"name": "Taliyah", "picks": 18, "bans": 9, "winrate": 55.6, "tier": "S"},
            {"name": "Akali", "picks": 6, "bans": 16, "winrate": 66.7, "tier": "S"},
            {"name": "Ziggs", "picks": 1, "bans": 18, "winrate": 100.0, "tier": "S"},
            {"name": "Neeko", "picks": 1, "bans": 15, "winrate": 100.0, "tier": "S"},
            {"name": "Ryze", "picks": 17, "bans": 5, "winrate": 41.2, "tier": "A"},
            {"name": "Aurora", "picks": 5, "bans": 15, "winrate": 60.0, "tier": "A"},
            {"name": "Yone", "picks": 4, "bans": 6, "winrate": 50.0, "tier": "B"},
            {"name": "Sylas", "picks": 2, "bans": 8, "winrate": 50.0, "tier": "B"},
            {"name": "Ahri", "picks": 6, "bans": 3, "winrate": 50.0, "tier": "B"},
            {"name": "Syndra", "picks": 2, "bans": 6, "winrate": 50.0, "tier": "B"},
            {"name": "Anivia", "picks": 4, "bans": 2, "winrate": 50.0, "tier": "B"},
            {"name": "Galio", "picks": 3, "bans": 3, "winrate": 66.7, "tier": "B"},
            {"name": "Annie", "picks": 1, "bans": 2, "winrate": 0.0, "tier": "B"},
            {"name": "Hwei", "picks": 2, "bans": 0, "winrate": 50.0, "tier": "B"},
            {"name": "Cassiopeia", "picks": 4, "bans": 9, "winrate": 25.0, "tier": "C"},
            {"name": "Viktor", "picks": 5, "bans": 5, "winrate": 20.0, "tier": "C"},
            {"name": "Veigar", "picks": 1, "bans": 0, "winrate": 100.0, "tier": "C"},
            {"name": "Tristana", "picks": 1, "bans": 0, "winrate": 0.0, "tier": "C"},
            {"name": "Twisted Fate", "picks": 1, "bans": 0, "winrate": 0.0, "tier": "C"},
        ],
        "ADC": [
            {"name": "Varus", "picks": 10, "bans": 38, "winrate": 60.0, "tier": "S"},
            {"name": "Yunara", "picks": 15, "bans": 9, "winrate": 60.0, "tier": "S"},
            {"name": "Ezreal", "picks": 11, "bans": 9, "winrate": 63.6, "tier": "A"},
            {"name": "Corki", "picks": 17, "bans": 1, "winrate": 52.9, "tier": "A"},
            {"name": "Senna", "picks": 2, "bans": 2, "winrate": 100.0, "tier": "A"},
            {"name": "Lucian", "picks": 10, "bans": 9, "winrate": 30.0, "tier": "B"},
            {"name": "Aphelios", "picks": 11, "bans": 3, "winrate": 45.5, "tier": "B"},
            {"name": "Jhin", "picks": 11, "bans": 2, "winrate": 36.4, "tier": "B"},
            {"name": "Kai'Sa", "picks": 11, "bans": 2, "winrate": 45.5, "tier": "B"},
            {"name": "Sivir", "picks": 5, "bans": 3, "winrate": 60.0, "tier": "B"},
            {"name": "Ashe", "picks": 5, "bans": 3, "winrate": 60.0, "tier": "B"},
            {"name": "Zeri", "picks": 1, "bans": 1, "winrate": 0.0, "tier": "B"},
            {"name": "Miss Fortune", "picks": 1, "bans": 1, "winrate": 100.0, "tier": "B"},
            {"name": "Kalista", "picks": 2, "bans": 0, "winrate": 50.0, "tier": "B"},
            {"name": "Xayah", "picks": 2, "bans": 2, "winrate": 50.0, "tier": "C"},
            {"name": "Sion", "picks": 1, "bans": 3, "winrate": 0.0, "tier": "C"},
            {"name": "Jinx", "picks": 1, "bans": 0, "winrate": 0.0, "tier": "C"},
            {"name": "Mel", "picks": 1, "bans": 0, "winrate": 0.0, "tier": "C"},
            {"name": "Smolder", "picks": 1, "bans": 0, "winrate": 0.0, "tier": "C"},
        ],
        "SUPPORT": [
            {"name": "Bard", "picks": 13, "bans": 18, "winrate": 46.2, "tier": "S"},
            {"name": "Nautilus", "picks": 7, "bans": 24, "winrate": 57.1, "tier": "S"},
            {"name": "Neeko", "picks": 12, "bans": 15, "winrate": 75.0, "tier": "S"},
            {"name": "Lulu", "picks": 10, "bans": 14, "winrate": 60.0, "tier": "S"},
            {"name": "Karma", "picks": 9, "bans": 14, "winrate": 66.7, "tier": "S"},
            {"name": "Poppy", "picks": 3, "bans": 10, "winrate": 100.0, "tier": "S"},
            {"name": "Nami", "picks": 16, "bans": 10, "winrate": 37.5, "tier": "A"},
            {"name": "Rakan", "picks": 9, "bans": 6, "winrate": 66.7, "tier": "A"},
            {"name": "Seraphine", "picks": 5, "bans": 0, "winrate": 60.0, "tier": "B"},
            {"name": "Braum", "picks": 3, "bans": 1, "winrate": 66.7, "tier": "B"},
            {"name": "Senna", "picks": 1, "bans": 2, "winrate": 0.0, "tier": "B"},
            {"name": "Milio", "picks": 1, "bans": 1, "winrate": 0.0, "tier": "B"},
            {"name": "Leona", "picks": 2, "bans": 0, "winrate": 100.0, "tier": "B"},
            {"name": "Alistar", "picks": 9, "bans": 3, "winrate": 22.2, "tier": "C"},
            {"name": "Rell", "picks": 8, "bans": 0, "winrate": 12.5, "tier": "C"},
            {"name": "Thresh", "picks": 4, "bans": 1, "winrate": 50.0, "tier": "C"},
            {"name": "Renata Glasc", "picks": 3, "bans": 2, "winrate": 33.3, "tier": "C"},
            {"name": "Blitzcrank", "picks": 1, "bans": 3, "winrate": 0.0, "tier": "C"},
            {"name": "Tahm Kench", "picks": 1, "bans": 0, "winrate": 0.0, "tier": "C"},
            {"name": "Sona", "picks": 1, "bans": 0, "winrate": 0.0, "tier": "C"},
        ],
    },
    "CBLOL": {  # 77 games
        "TOP": [
            {"name": "Rumble", "picks": 32, "bans": 20, "winrate": 50.0, "tier": "S"},
            {"name": "Jayce", "picks": 1, "bans": 51, "winrate": 100.0, "tier": "S"},
            {"name": "Ambessa", "picks": 16, "bans": 35, "winrate": 62.5, "tier": "S"},
            {"name": "Renekton", "picks": 16, "bans": 26, "winrate": 62.5, "tier": "S"},
            {"name": "Akali", "picks": 1, "bans": 35, "winrate": 100.0, "tier": "S"},
            {"name": "K'Sante", "picks": 19, "bans": 9, "winrate": 52.6, "tier": "A"},
            {"name": "Sion", "picks": 18, "bans": 5, "winrate": 61.1, "tier": "A"},
            {"name": "Gnar", "picks": 11, "bans": 4, "winrate": 36.4, "tier": "B"},
            {"name": "Gwen", "picks": 5, "bans": 10, "winrate": 40.0, "tier": "B"},
            {"name": "Jax", "picks": 6, "bans": 3, "winrate": 50.0, "tier": "B"},
            {"name": "Aurora", "picks": 2, "bans": 1, "winrate": 50.0, "tier": "B"},
            {"name": "Ornn", "picks": 3, "bans": 0, "winrate": 66.7, "tier": "B"},
            {"name": "Yorick", "picks": 2, "bans": 0, "winrate": 0.0, "tier": "B"},
            {"name": "Camille", "picks": 2, "bans": 0, "winrate": 100.0, "tier": "B"},
            {"name": "Galio", "picks": 1, "bans": 1, "winrate": 0.0, "tier": "B"},
            {"name": "Poppy", "picks": 1, "bans": 9, "winrate": 0.0, "tier": "C"},
            {"name": "Zaahen", "picks": 5, "bans": 4, "winrate": 20.0, "tier": "C"},
            {"name": "Aatrox", "picks": 4, "bans": 2, "winrate": 0.0, "tier": "C"},
            {"name": "Rek'Sai", "picks": 5, "bans": 1, "winrate": 40.0, "tier": "C"},
            {"name": "Kennen", "picks": 2, "bans": 4, "winrate": 50.0, "tier": "C"},
            {"name": "Olaf", "picks": 1, "bans": 0, "winrate": 0.0, "tier": "C"},
            {"name": "Vayne", "picks": 1, "bans": 0, "winrate": 0.0, "tier": "C"},
        ],
        "JUNGLE": [
            {"name": "Jayce", "picks": 6, "bans": 51, "winrate": 50.0, "tier": "S"},
            {"name": "Malphite", "picks": 4, "bans": 44, "winrate": 50.0, "tier": "S"},
            {"name": "Jarvan IV", "picks": 28, "bans": 15, "winrate": 39.3, "tier": "S"},
            {"name": "Ambessa", "picks": 4, "bans": 35, "winrate": 50.0, "tier": "S"},
            {"name": "Pantheon", "picks": 16, "bans": 22, "winrate": 43.8, "tier": "S"},
            {"name": "Qiyana", "picks": 7, "bans": 19, "winrate": 85.7, "tier": "S"},
            {"name": "Xin Zhao", "picks": 21, "bans": 4, "winrate": 38.1, "tier": "A"},
            {"name": "Nocturne", "picks": 9, "bans": 11, "winrate": 66.7, "tier": "A"},
            {"name": "Vi", "picks": 16, "bans": 3, "winrate": 56.2, "tier": "A"},
            {"name": "Zaahen", "picks": 1, "bans": 4, "winrate": 100.0, "tier": "A"},
            {"name": "Wukong", "picks": 18, "bans": 1, "winrate": 50.0, "tier": "B"},
            {"name": "Aatrox", "picks": 9, "bans": 2, "winrate": 55.6, "tier": "B"},
            {"name": "Trundle", "picks": 2, "bans": 0, "winrate": 50.0, "tier": "B"},
            {"name": "Skarner", "picks": 2, "bans": 0, "winrate": 100.0, "tier": "B"},
            {"name": "Dr. Mundo", "picks": 4, "bans": 1, "winrate": 50.0, "tier": "C"},
            {"name": "Gnar", "picks": 1, "bans": 4, "winrate": 0.0, "tier": "C"},
            {"name": "Sejuani", "picks": 3, "bans": 1, "winrate": 33.3, "tier": "C"},
            {"name": "Lee Sin", "picks": 1, "bans": 0, "winrate": 0.0, "tier": "C"},
            {"name": "Naafiri", "picks": 1, "bans": 0, "winrate": 100.0, "tier": "C"},
            {"name": "Nidalee", "picks": 1, "bans": 0, "winrate": 100.0, "tier": "C"},
        ],
        "MID": [
            {"name": "Orianna", "picks": 16, "bans": 43, "winrate": 37.5, "tier": "S"},
            {"name": "Ryze", "picks": 29, "bans": 18, "winrate": 37.9, "tier": "S"},
            {"name": "Akali", "picks": 7, "bans": 35, "winrate": 71.4, "tier": "S"},
            {"name": "Taliyah", "picks": 18, "bans": 10, "winrate": 55.6, "tier": "A"},
            {"name": "Syndra", "picks": 10, "bans": 12, "winrate": 80.0, "tier": "A"},
            {"name": "Ahri", "picks": 12, "bans": 6, "winrate": 66.7, "tier": "A"},
            {"name": "Mel", "picks": 1, "bans": 3, "winrate": 100.0, "tier": "A"},
            {"name": "Sylas", "picks": 4, "bans": 10, "winrate": 50.0, "tier": "B"},
            {"name": "Aurora", "picks": 12, "bans": 1, "winrate": 41.7, "tier": "B"},
            {"name": "LeBlanc", "picks": 2, "bans": 10, "winrate": 50.0, "tier": "B"},
            {"name": "Cassiopeia", "picks": 7, "bans": 3, "winrate": 71.4, "tier": "B"},
            {"name": "Anivia", "picks": 3, "bans": 1, "winrate": 66.7, "tier": "B"},
            {"name": "Azir", "picks": 8, "bans": 8, "winrate": 25.0, "tier": "C"},
            {"name": "Zoe", "picks": 6, "bans": 6, "winrate": 33.3, "tier": "C"},
            {"name": "Viktor", "picks": 5, "bans": 3, "winrate": 40.0, "tier": "C"},
            {"name": "Galio", "picks": 6, "bans": 1, "winrate": 50.0, "tier": "C"},
            {"name": "Yone", "picks": 4, "bans": 1, "winrate": 50.0, "tier": "C"},
            {"name": "Ekko", "picks": 1, "bans": 0, "winrate": 0.0, "tier": "C"},
            {"name": "Tristana", "picks": 1, "bans": 0, "winrate": 100.0, "tier": "C"},
            {"name": "Twisted Fate", "picks": 1, "bans": 0, "winrate": 100.0, "tier": "C"},
            {"name": "Hwei", "picks": 1, "bans": 0, "winrate": 0.0, "tier": "C"},
        ],
        "ADC": [
            {"name": "Varus", "picks": 13, "bans": 60, "winrate": 76.9, "tier": "S"},
            {"name": "Ezreal", "picks": 20, "bans": 20, "winrate": 55.0, "tier": "S"},
            {"name": "Corki", "picks": 23, "bans": 14, "winrate": 34.8, "tier": "A"},
            {"name": "Yunara", "picks": 24, "bans": 9, "winrate": 50.0, "tier": "A"},
            {"name": "Sivir", "picks": 12, "bans": 11, "winrate": 50.0, "tier": "A"},
            {"name": "Xayah", "picks": 4, "bans": 4, "winrate": 100.0, "tier": "A"},
            {"name": "Sion", "picks": 1, "bans": 5, "winrate": 100.0, "tier": "A"},
            {"name": "Kai'Sa", "picks": 12, "bans": 5, "winrate": 33.3, "tier": "B"},
            {"name": "Aphelios", "picks": 4, "bans": 13, "winrate": 50.0, "tier": "B"},
            {"name": "Lucian", "picks": 10, "bans": 6, "winrate": 40.0, "tier": "B"},
            {"name": "Ashe", "picks": 6, "bans": 9, "winrate": 50.0, "tier": "B"},
            {"name": "Jhin", "picks": 9, "bans": 1, "winrate": 55.6, "tier": "B"},
            {"name": "Miss Fortune", "picks": 6, "bans": 2, "winrate": 66.7, "tier": "B"},
            {"name": "Caitlyn", "picks": 3, "bans": 4, "winrate": 33.3, "tier": "C"},
            {"name": "Kalista", "picks": 2, "bans": 2, "winrate": 0.0, "tier": "C"},
            {"name": "Tristana", "picks": 1, "bans": 0, "winrate": 100.0, "tier": "C"},
            {"name": "Zeri", "picks": 1, "bans": 0, "winrate": 0.0, "tier": "C"},
            {"name": "Smolder", "picks": 1, "bans": 0, "winrate": 0.0, "tier": "C"},
            {"name": "Jinx", "picks": 1, "bans": 0, "winrate": 0.0, "tier": "C"},
            {"name": "Ziggs", "picks": 1, "bans": 0, "winrate": 100.0, "tier": "C"},
        ],
        "SUPPORT": [
            {"name": "Bard", "picks": 19, "bans": 24, "winrate": 57.9, "tier": "S"},
            {"name": "Neeko", "picks": 11, "bans": 30, "winrate": 54.5, "tier": "S"},
            {"name": "Alistar", "picks": 18, "bans": 9, "winrate": 72.2, "tier": "S"},
            {"name": "Nautilus", "picks": 13, "bans": 18, "winrate": 23.1, "tier": "A"},
            {"name": "Nami", "picks": 17, "bans": 7, "winrate": 41.2, "tier": "A"},
            {"name": "Rakan", "picks": 16, "bans": 7, "winrate": 56.2, "tier": "A"},
            {"name": "Leona", "picks": 18, "bans": 2, "winrate": 50.0, "tier": "A"},
            {"name": "Ashe", "picks": 1, "bans": 9, "winrate": 100.0, "tier": "A"},
            {"name": "Karma", "picks": 5, "bans": 14, "winrate": 40.0, "tier": "B"},
            {"name": "Lulu", "picks": 10, "bans": 6, "winrate": 40.0, "tier": "B"},
            {"name": "Seraphine", "picks": 7, "bans": 4, "winrate": 42.9, "tier": "B"},
            {"name": "Rell", "picks": 7, "bans": 1, "winrate": 57.1, "tier": "B"},
            {"name": "Milio", "picks": 4, "bans": 0, "winrate": 75.0, "tier": "B"},
            {"name": "Senna", "picks": 1, "bans": 2, "winrate": 100.0, "tier": "B"},
            {"name": "Renata Glasc", "picks": 2, "bans": 0, "winrate": 0.0, "tier": "B"},
            {"name": "Poppy", "picks": 1, "bans": 9, "winrate": 0.0, "tier": "C"},
            {"name": "Thresh", "picks": 1, "bans": 3, "winrate": 0.0, "tier": "C"},
            {"name": "Pyke", "picks": 1, "bans": 0, "winrate": 0.0, "tier": "C"},
            {"name": "Blitzcrank", "picks": 1, "bans": 0, "winrate": 0.0, "tier": "C"},
            {"name": "Yuumi", "picks": 1, "bans": 0, "winrate": 100.0, "tier": "C"},
        ],
    },
}
